### ISSUE TITLE
calendar reminder home assistant

### ISSUE THREAD

**Issue by runtimevic** [home-assistant/custom-panel-starter-kit-react#10]
Hello, very good job congratulations.
I don't know how to do a project from scratch with redux from scratch and I have tried adding it in the home assistant panel and I don't get anything in the internet browser.
I would like to be able to carry out a calendar project with a reminder and that the different home assistant entities could be set up and that for events according to the time the different events were carried out

**Comment by frenck** [comment]
This repository is deprecated and will be archived.
