### ISSUE TITLE
Install renders in white page with js console errors

### ISSUE THREAD

**Issue by CubieMedia** [home-assistant/custom-panel-starter-kit-react#2]
Trying to use this starter kit with:

home-assistant 0.84.0.dev0 (clean install)

adjusted configuration.yaml as descriped in the README
server has been started with yarn start and is sending main.js on localhost:8080/main.js

Should this still work with the current version of HA?

**Comment by StonedOne** [comment]
/home/ogruss/Bilder/Bildschirmfoto von 2018-11-29 11-20-39.png

**Comment by CubieMedia** [comment]
![bildschirmfoto von 2018-11-29 11-20-39](https://user-images.githubusercontent.com/7445772/49215491-34866880-f3c9-11e8-8723-8ba004b607fb.png)

**Comment by CubieMedia** [comment]
In EntityRow.js i set
`canToggle = true`
with this i started to develop my first panel.

Thanks for this template

**Comment by andrewlphilpott** [comment]
I was having the same issue while running this on 0.88 and found that I had to change line 22 of EntityRow.js to this:

```
const canToggle = true in (hass.services[domain] || {})
```

Looks like `services` is no longer a property of `config`
